"""add promotions table

Revision ID: 0727ffe26dbd
Revises: e5f6g7h8i9j0
Create Date: 2025-11-23 20:18:23.297238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0727ffe26dbd'
down_revision = 'e5f6g7h8i9j0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
