"""init schema (fixed zip)

Revision ID: 2255337d3857
Revises: 8c288dedde53
Create Date: 2025-09-26 01:00:13.663165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2255337d3857'
down_revision = '8c288dedde53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_info')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'], postgresql_nulls_not_distinct=False)

    op.create_table('billing_info',
    sa.Column('billing_info_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('card_type', postgresql.ENUM('debit', 'credit', name='card_type_enum'), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('card_exp', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('billing_street', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('billing_state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('billing_zip_code', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("card_number::text ~ '^[0-9]{16}$'::text", name=op.f('ck_card_number_digits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('billing_info_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('billing_info_id', name=op.f('billing_info_pkey'))
    )
    # ### end Alembic commands ###
