"""add showtimes table

Revision ID: 2894842e7407
Revises: 2255337d3857
Create Date: 2025-09-26 15:47:40.740042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2894842e7407'
down_revision = '2255337d3857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtimes',
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('auditorium_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('child_price_cents', sa.Integer(), nullable=False),
    sa.Column('adult_price_cents', sa.Integer(), nullable=False),
    sa.Column('senior_price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditoriums.auditorium_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('showtime_id'),
    sa.UniqueConstraint('auditorium_id', 'starts_at', name='uq_showtimes_aud_start')
    )
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_showtimes_auditorium_id'), ['auditorium_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_showtimes_movie_id'), ['movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_showtimes_movie_id'))
        batch_op.drop_index(batch_op.f('ix_showtimes_auditorium_id'))

    op.drop_table('showtimes')
    # ### end Alembic commands ###
