"""update users schema add billinginfo table

Revision ID: 480f1a9532ed
Revises: 2894842e7407
Create Date: 2025-10-23 05:30:08.504680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480f1a9532ed'
down_revision = '2894842e7407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_info',
    sa.Column('billing_info_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cardholder_name', sa.Text(), nullable=False),
    sa.Column('card_type', sa.Enum('debit', 'credit', name='card_type_enum'), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('card_exp', sa.String(length=5), nullable=False),
    sa.Column('billing_street', sa.Text(), nullable=False),
    sa.Column('billing_state', sa.Text(), nullable=False),
    sa.Column('billing_zip_code', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("card_number ~ '^[0-9]{16}$'", name='ck_card_number_digits'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('billing_info_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    op.drop_table('billing_info')
    # ### end Alembic commands ###
