"""add num rows and cols to auditorium

Revision ID: 50d6ae560722
Revises: 8b8dd892822e
Create Date: 2025-11-23 20:59:24.119491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d6ae560722'
down_revision = '8b8dd892822e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoriums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('col_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoriums', schema=None) as batch_op:
        batch_op.drop_column('col_count')
        batch_op.drop_column('row_count')

    # ### end Alembic commands ###
