"""(fix)add seathold and ticket constraints

Revision ID: 80d1be6670b6
Revises: 50d6ae560722
Create Date: 2025-11-24 04:23:28.221058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d1be6670b6'
down_revision = '50d6ae560722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat_holds', schema=None) as batch_op:
        batch_op.create_index('uq_seat_holds_active', ['showtime_id', 'seat_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tickets_showtime_seat', ['showtime_id', 'seat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tickets_showtime_seat', type_='unique')

    with op.batch_alter_table('seat_holds', schema=None) as batch_op:
        batch_op.drop_index('uq_seat_holds_active', postgresql_where=sa.text('released_at IS NULL'))

    # ### end Alembic commands ###
