"""add promotions table

Revision ID: 8b8dd892822e
Revises: 0727ffe26dbd
Create Date: 2025-11-23 20:19:34.873004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8dd892822e'
down_revision = '0727ffe26dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percent > 0 AND discount_percent <= 100', name='ck_promotions_discount_range'),
    sa.CheckConstraint('max_uses IS NULL OR max_uses >= 0', name='ck_promotions_max_uses_nonneg'),
    sa.CheckConstraint('per_user_limit IS NULL OR per_user_limit >= 0', name='ck_promotions_per_user_nonneg'),
    sa.CheckConstraint('starts_at < ends_at', name='ck_promotions_date_range'),
    sa.PrimaryKeyConstraint('promotion_id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('ix_promotions_code', ['code'], unique=False)
        batch_op.create_index('ix_promotions_validity_window', ['starts_at', 'ends_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index('ix_promotions_validity_window')
        batch_op.drop_index('ix_promotions_code')

    op.drop_table('promotions')
    # ### end Alembic commands ###
