"""init schema

Revision ID: 8c288dedde53
Revises: 
Create Date: 2025-09-26 00:53:35.306236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c288dedde53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoriums',
    sa.Column('auditorium_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('auditorium_id'),
    sa.UniqueConstraint('name', name='uq_auditoriums_name')
    )
    with op.batch_alter_table('auditoriums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoriums_name'), ['name'], unique=False)

    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cast', sa.Text(), nullable=True),
    sa.Column('director', sa.Text(), nullable=True),
    sa.Column('producer', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('trailer_picture', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('film_rating_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_title'), ['title'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_email_list', sa.Boolean(), nullable=True),
    sa.Column('home_street', sa.Text(), nullable=True),
    sa.Column('home_city', sa.Text(), nullable=True),
    sa.Column('home_state', sa.Text(), nullable=True),
    sa.Column('home_country', sa.Text(), nullable=True),
    sa.Column('home_zip_code', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.UniqueConstraint("email", name="uq_users_email"),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('billing_info',
    sa.Column('billing_info_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('card_type', sa.Enum('debit', 'credit', name='card_type_enum'), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('card_exp', sa.String(length=5), nullable=False),
    sa.Column('billing_street', sa.Text(), nullable=False),
    sa.Column('billing_state', sa.Text(), nullable=False),
    sa.Column('billing_zip_code', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("card_number ~ '^[0-9]{16}$'", name='ck_card_number_digits'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('billing_info_id')
    )
    op.create_table('movie_categories',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_categories')
    op.drop_table('billing_info')
    op.drop_table('users')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_title'))

    op.drop_table('movies')
    op.drop_table('categories')
    with op.batch_alter_table('auditoriums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoriums_name'))

    op.drop_table('auditoriums')
    # ### end Alembic commands ###
