"""increase card fields for encryption

Revision ID: e5f6g7h8i9j0
Revises: ffffffffffffffff
Create Date: 2025-11-19 02:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6g7h8i9j0'
down_revision = 'ffffffffffffffff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old CHECK constraint on card_number (no longer valid for encrypted data)
    with op.batch_alter_table('billing_info', schema=None) as batch_op:
        batch_op.drop_constraint('ck_card_number_digits', type_='check')
        
        # Expand card_number from String(16) to String(255) for encrypted data
        batch_op.alter_column('card_number',
                   existing_type=sa.String(length=16),
                   type_=sa.String(length=255),
                   existing_nullable=False)
        
        # Expand card_exp from String(5) to String(255) for encrypted data
        batch_op.alter_column('card_exp',
                   existing_type=sa.String(length=5),
                   type_=sa.String(length=255),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_info', schema=None) as batch_op:
        # Revert card_exp from String(255) to String(5)
        batch_op.alter_column('card_exp',
                   existing_type=sa.String(length=255),
                   type_=sa.String(length=5),
                   existing_nullable=False)
        
        # Revert card_number from String(255) to String(16)
        batch_op.alter_column('card_number',
                   existing_type=sa.String(length=255),
                   type_=sa.String(length=16),
                   existing_nullable=False)
        
        # Re-add the CHECK constraint
        batch_op.create_check_constraint('ck_card_number_digits',
                                         "card_number ~ '^[0-9]{16}$'")
    # ### end Alembic commands ###
